#!/usr/bin/env node
'use strict'

const queue = require('queue')
const job = require('./job')
const groupBy = require('lodash.groupby')
const ProgressBar = require('ascii-progress')
const lines = require('./data/attendance-units.json')

const groups = Object.values(groupBy(lines, (line) => line.CNPJ.substr(0, 8)))

const progress = new ProgressBar({
  total: groups.length,
  schema: '[:bar] :current/:total :percent :elapseds/:etas. :errors errors'
})

const errors = []

const q = queue({
  concurrency: 50
})

const jobs = groups.map((group) => job.factory(group))

q.push(...jobs)

q.on('success', () => {
  progress.tick({ errors: errors.length })
})

q.on('error', err => {
  progress.tick({ errors: errors.length })

  if (err.message.includes('ENOTFOUND') || err.message.includes('ECONNRESET')) {
    progress.total++
    q.push(job.factory(err.group))
    return
  }

  if (!err.response) {
    return errors.push(`${err.mainCnpj}: ${err.message}`)
  }

  errors.push(`${err.mainCnpj}: ${err.response.data.error.message}`)
})

q.on('end', () => {
  console.log(`Errors (${errors.length}):`)
  console.log(errors.join('\n'))
  process.exit(0)
})

q.start()
